### ISSUE TITLE
NoSuchMethodError after upgrading from 2.2.6 to 2.3.0

### ISSUE THREAD

**Issue by ball3t** [MorphiaOrg/morphia#2235]
After upgrading from 2.2.6 to 2.3, I changed the filter from dev.morphia.query.experimental.filters.Filters to dev.morphia.query.filters.Filters.
when calling filter().first(), this exception is thrown.

Request failed: java.lang.NoSuchMethodError: com.mongodb.client.FindIterable.comment(Lorg/bson/BsonValue;)Lcom/mongodb/client/FindIterable;
	at dev.morphia.query.FindOptions.apply(FindOptions.java:125)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:336)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:220)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:197)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:192)

After looking at the source code, it was:
`iterable.comment(comment);`

and comment is a BsonValue.

from the mongodb driver doc, shouldn't the comment be a string?
http://mongodb.github.io/mongo-java-driver/4.3/apidocs/mongodb-driver-sync/com/mongodb/client/FindIterable.html

or am i missing sth?

Thanks.

** Please complete the following information: **
    Server Version: 6.0
    Driver Version: 4.3.4
    Morphia Version: 2.3.0

Regards,
BaLL

**Comment by evanchooly** [comment]
That method on the driver changed in 4.6 to take a `BsonValue` so internally Morphia converts the `String` comment to a `BsonString` to conform.  Try updating you driver version and you should be set.  If upgrading the driver isn't an option, we can explore some alternatives that might be a better fit.

This kind of drift with the driver API doesn't have a clean solution yet in Morphia though I have some pieces in place to try and track/catch them better.  It's part of the plan in the coming weeks/months to build out the necessary bits to catch these more proactively and try to mitigate them.

**Comment by ball3t** [comment]
For this time I can update the driver.
Tested with latest driver 4.8.2, it is working now.
Is there any "officially" preferred mongodb driver version for morphia?

**Comment by evanchooly** [comment]
In general, the latest is best.  Ideally, the java driver wouldn't be directly listed in your pom/gradle build and it would just get pulled in as a transitive dependency but I know that's not always an option.

I've tried to make Morphia fairly agnostic in terms of driver versions but until recently, there hasn't really been the capability of testing against older versions at any sort of scale.  i intend to add some tests in the CI matrix for using older versions and seeing where things break and trying to mitigate those inside Morphia where I can.

**Comment by evanchooly** [comment]
closing this as the CI matrix seems to indicate things work with older drivers, too.
